version: "3"
services:
  web-prod:
    image: nginx:alpine
    ports:
      - target: 80
        published: 8080
    restart: always
    networks:
      - web

  web-qa:
    image: nginx:alpine
    ports:
      - target: 80
        published: 8081
    restart: always
    networks:
      - web

  web-dev:
    build: ./app
    ports:
      - target: 80
        published: 8082
    restart: always
    networks:
      - web

networks:
  web:
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"